FROM golang:alpine AS builder
RUN apk --no-cache add gcc g++ make git
# uncomment following two lines if clone open source project from Github
# WORKDIR /go/src
# RUN git clone -b master git@github.com:acebeing/gitery.git
WORKDIR /go/src/gitery
# Copy source file from local to container
COPY . .
RUN go get
RUN GOOS=linux go build -ldflags="-s -w" -o ./bin/gitery ./cmd/gitery

FROM alpine:3.9
RUN apk --no-cache add ca-certificates
WORKDIR /usr/bin
COPY --from=builder /go/src/gitery/bin /go/bin
EXPOSE 80
ENTRYPOINT /go/bin/gitery --port 80