DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS posts cascade;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS tags cascade;
DROP TABLE IF EXISTS post_tag;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	hashed_pwd VARCHAR(255) UNIQUE NOT NULL,
	nickname VARCHAR(255) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE posts (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE comments(
	id SERIAL PRIMARY KEY,
	content TEXT NOT NULL,
	post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	parent_id INTEGER REFERENCES comments(id),
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE tags(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE post_tag(
	post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
	tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE,
	PRIMARY KEY (post_id, tag_id)
);
