###### build locally and deploy executable file to server ########
FROM alpine:latest
ARG app_env
ENV APP_ENV $app_env
RUN apk --no-cache add ca-certificates
WORKDIR /usr/bin
COPY ./bin /go/bin
EXPOSE 80
ENTRYPOINT /go/bin/gitery --port 80